### ISSUE TITLE
Always on?

### ISSUE THREAD

**Issue by hamen** [PDDStudio/Talk#1]
Hi and congrats for the project: it looks very cool!
Do you think this could be used as an _always waiting for commands_ app?
I mean, like some sort of Google Now, but with a different set of triggers.
Thanks :)

**Comment by PDDStudio** [comment]
Hi @hamen,
I was already looking for this, what I found out so far:
- You cannot trigger a custom hotword like 'Ok Google' does to start listening for voice input
- You can implement a background service to permanently listen for voice actions (this means it will record all voice input which it can find as soon as the service is started and always makes this kinda beep when listening)

Br

**Comment by hamen** [comment]
I'm thinking about Amazon Echo or Iron Man's Jarvis, waiting for:
"Hal, turn on the light" -> triggering a POST to turn on my Hue.
The service could work, but I don't get the "beep" thing. Will it "beep" when a trigger word is captured, i.e. "Hal" -> beep -> "Turn on the light" or what?

**Comment by PDDStudio** [comment]
@hamen it will make the same "beep" as google does after you said 'Ok Google' (the feedback which let's you know that it's listening now)

**Comment by hamen** [comment]
Patrick, I think that's perfect! I need to try something with Talk and these
https://github.com/HannahMitt/HomeMirror
https://github.com/ineptech/mirror
Tiiiiime!!! I need moar tiiime!!! :joy:

**Comment by AdrianVovk** [comment]
@PDDStudio why wouldn't you be able to inpliment something like "Ok Google"?

**Comment by PDDStudio** [comment]
@AnimbusDev well you could - in theory - but it won't have the same behavior as 'Ok Google' has. As mentioned above, you could implement a background service which listens all the time for a custom HotWord and then triggers a new Listener which listens for the voice command.

**Comment by PDDStudio** [comment]
I'm going to close this for now as there's not any efficient way of achieving the desired behavior.
